### ISSUE TITLE
关于您的博客

### ISSUE THREAD

**Issue by yo1995** [flinhong/flinhong.github.io#1]
看了您的博客https://flinhong.com/觉得风格不错，想了解一下是基于哪个模板修改、具体是用哪些方案实现的。
翻了一下博文没有找到相关的内容。您在github的repo也比较乱，不知该fork哪些内容。好像有多种模板？
http://photo.flinhong.com/
https://flinhong.github.io/
https://flinhong.com/
都不一样……

**Comment by flinhong** [comment]
呵呵，不好意思确实有点乱，有时间整理整理。其实readme里面有写应该fork哪个仓库，目前来说就是blog那个repo，Jekyll的文件在blog的deploy分支里面。

**Comment by flinhong** [comment]
[flinhong.github.io](https://flinhong.github.io)这个模板是找到纯HTML模板改的，没有使用框架~

**Comment by yo1995** [comment]
好的，谢谢！我研究一下^ ^
看到您的博客再看自己的……见异思迁了:flushed:

**Comment by flinhong** [comment]
一样一样。我已经换过好几个博客模板了
